/*
 * This source file was generated by the Gradle 'init' task
 */
package advent.of.code;

public class App {

    public static void main(String[] args) throws Exception {
        System.out.println("AOC 2025");
    }

}
